const fs = require("fs");
const path = require("path");

const {
  IOSConfig,
  withXcodeProject,
} = require("@expo/config-plugins");

const { XcodeUtils } = IOSConfig;

const SWIFT_FILE_NAME = "AnimuAppIntents.swift";
const STRINGS_FILE_NAME = "AppShortcuts.strings";

/**
 * Trigger phrases per locale, in lockstep order. The English list is the
 * source of truth: it drives the Swift `AppShortcut` declarations, and every
 * other locale reuses its keys with a translated value.
 *
 * Rules the App Intents runtime enforces (see AppStore review rejections):
 *  - Every phrase MUST contain the `applicationName` token.
 *  - A locale's `.strings` file must declare exactly the same keys as the
 *    Swift source, so the app-name substitution still resolves.
 *  - Keep verbs natural for the locale; Siri matches these literally, so a
 *    near-miss phrasing ("tocar", "ouvir", "play") is what fails activation.
 */
const PHRASE_TRANSLATIONS = {
  en: [
    "Play ${applicationName}",
    "Play radio ${applicationName}",
    "Play Japanese radio on ${applicationName}",
    "Play anime radio on ${applicationName}",
    "Start ${applicationName}",
    "Start radio on ${applicationName}",
    "Listen to ${applicationName}",
    "Listen to radio on ${applicationName}",
    "Listen to Japanese radio on ${applicationName}",
    "Resume ${applicationName}",
  ],
  "pt-BR": [
    "Tocar ${applicationName}",
    "Tocar rádio ${applicationName}",
    "Tocar rádio japonesa no ${applicationName}",
    "Tocar rádio de anime no ${applicationName}",
    "Iniciar ${applicationName}",
    "Iniciar rádio no ${applicationName}",
    "Ouvir ${applicationName}",
    "Ouvir rádio no ${applicationName}",
    "Ouvir rádio japonesa no ${applicationName}",
    "Reproduzir rádio no ${applicationName}",
  ],
  es: [
    "Reproducir ${applicationName}",
    "Reproducir radio ${applicationName}",
    "Reproducir radio japonesa en ${applicationName}",
    "Reproducir radio de anime en ${applicationName}",
    "Iniciar ${applicationName}",
    "Iniciar radio en ${applicationName}",
    "Escuchar ${applicationName}",
    "Escuchar radio en ${applicationName}",
    "Escuchar radio japonesa en ${applicationName}",
    "Poner ${applicationName}",
  ],
  ja: [
    "${applicationName}を再生",
    "${applicationName}のラジオを再生",
    "${applicationName}で日本のラジオを再生",
    "${applicationName}でアニメラジオを再生",
    "${applicationName}を開始",
    "${applicationName}でラジオを開始",
    "${applicationName}を聞く",
    "${applicationName}でラジオを聞く",
    "${applicationName}で日本のラジオを聞く",
    "${applicationName}をかけて",
  ],
};

/** Locale folders Siri phrase localization is generated for. */
const LOCALES = Object.keys(PHRASE_TRANSLATIONS);

/**
 * Base (English) phrase keys. The key is what the Swift `AppShortcutPhrase`
 * literal contains, with `\(.applicationName)` written as
 * `${applicationName}` — that token is what the App Intents runtime
 * substitutes at build time.
 */
const PHRASE_KEYS = PHRASE_TRANSLATIONS.en;

/** `"Play ${applicationName}"` → `"Play \(.applicationName)"` for Swift. */
function toSwiftPhrase(phrase) {
  return phrase.replace("${applicationName}", "\\(.applicationName)");
}

function buildSwiftSource() {
  const phrases = PHRASE_KEYS.map(
    (phrase) => `                "${toSwiftPhrase(phrase)}",`,
  ).join("\n");

  return `import AppIntents
import UIKit

/**
 * Siri / Shortcuts entry point for "Hey Siri, play R\u00e1dio Animu".
 *
 * The intent does not touch the player directly \u2014 it opens the same deep link
 * Google App Actions uses, so both assistants share one JS contract
 * (\`animuapp://assistant/play\`).
 */
@available(iOS 16.0, *)
struct PlayAnimuIntent: AppIntent {
    static var title: LocalizedStringResource = "Play R\u00e1dio Animu"
    static var description = IntentDescription("Starts playing R\u00e1dio Animu.")

    // Bring the app forward so the URL can be delivered to the running app.
    static var openAppWhenRun: Bool = true

    @MainActor
    func perform() async throws -> some IntentResult {
        if let url = URL(string: "animuapp://assistant/play") {
            await UIApplication.shared.open(url)
        }
        return .result()
    }
}

/**
 * Phrases registered with the system. Every phrase must contain
 * \\(.applicationName) so Siri can disambiguate apps. Localized variants live in
 * \`AppShortcuts.strings\` (generated by plugins/withIOSAppIntents.js).
 *
 * GENERATED \u2014 edit the plugin, not this file.
 */
@available(iOS 16.0, *)
struct AnimuAppShortcuts: AppShortcutsProvider {
    static var appShortcuts: [AppShortcut] {
        AppShortcut(
            intent: PlayAnimuIntent(),
            phrases: [
${phrases}
            ],
            shortTitle: "Play R\u00e1dio Animu",
            systemImageName: "play.circle.fill"
        )
    }
}
`;
}

const SWIFT_SOURCE = buildSwiftSource();

function stringsContent(locale) {
  const translations = PHRASE_TRANSLATIONS[locale];
  return PHRASE_KEYS.map(
    (key, index) => `"${key}" = "${translations[index]}";`,
  ).join("\n") + "\n";
}

/** Writes the Swift source and localized phrase tables into the app folder. */
function writeSourceFiles(projectRoot, projectName) {
  const appDir = path.join(projectRoot, "ios", projectName);
  fs.mkdirSync(appDir, { recursive: true });
  fs.writeFileSync(path.join(appDir, SWIFT_FILE_NAME), SWIFT_SOURCE);

  for (const locale of LOCALES) {
    const lproj = path.join(appDir, `${locale}.lproj`);
    fs.mkdirSync(lproj, { recursive: true });
    fs.writeFileSync(path.join(lproj, STRINGS_FILE_NAME), stringsContent(locale));
  }
}

/** Adds the Swift file to the app target's compile sources. */
function addSwiftSource(config, projectName) {
  const project = config.modResults;
  const relativePath = `${projectName}/${SWIFT_FILE_NAME}`;
  XcodeUtils.addBuildSourceFileToGroup({
    filepath: relativePath,
    groupName: projectName,
    project,
  });
}

/**
 * Registers `AppShortcuts.strings` as a localized resource. Each locale lives in
 * its own `.lproj` and is grouped under a single variant group so Xcode copies
 * it into the matching bundle subdirectory.
 */
function addLocalizedPhrases(config, projectName) {
  const project = config.modResults;

  // Repeated (non-clean) prebuilds must not stack duplicate variant groups.
  if (project.findPBXVariantGroupKey({ name: STRINGS_FILE_NAME })) {
    return;
  }

  const variantGroup = project.addLocalizationVariantGroup(STRINGS_FILE_NAME);
  const groupKey = variantGroup.fileRef;

  // `pbxFile` is xcode's file model; `basename` becomes the variant's `name`
  // (the locale) while `path` keeps the `.lproj` folder.
  const PbxFile = require("xcode/lib/pbxFile");

  for (const locale of LOCALES) {
    const relativePath = `${projectName}/${locale}.lproj/${STRINGS_FILE_NAME}`;
    const file = new PbxFile(relativePath);
    file.basename = locale;
    file.uuid = project.generateUuid();
    file.fileRef = project.generateUuid();
    project.addToPbxFileReferenceSection(file);
    project.addToPbxVariantGroup(file, groupKey);
    project.addKnownRegion(locale);
  }
}

module.exports = function withIOSAppIntents(config) {
  return withXcodeProject(config, (config) => {
    const projectRoot = config.modRequest.projectRoot;
    const projectName = XcodeUtils.getProjectName(projectRoot);

    writeSourceFiles(projectRoot, projectName);
    addSwiftSource(config, projectName);

    // Localization is best-effort: if the variant group cannot be created the
    // app still builds with the English phrases baked into the Swift source.
    try {
      addLocalizedPhrases(config, projectName);
    } catch (error) {
      console.warn(
        "[withIOSAppIntents] Could not register AppShortcuts.strings localizations:",
        error,
      );
    }

    return config;
  });
};

module.exports.PHRASE_KEYS = PHRASE_KEYS;
module.exports.PHRASE_TRANSLATIONS = PHRASE_TRANSLATIONS;
module.exports.buildSwiftSource = buildSwiftSource;
module.exports.stringsContent = stringsContent;
